import { icons } from "./icons";

export const tabs: AppTab[] = [
  { name: "index", title: "Home", icon: icons.home },
  { name: "settings", title: "Settings", icon: icons.setting },
];

// Protected tabs - accessible after authentication
export const protectedTabs: AppTab[] = [
  { name: "subscriptions", title: "Subscriptions", icon: icons.wallet },
  { name: "insights", title: "Insights", icon: icons.activity },
];

export const HOME_USER = {
  name: "Oreo",
};

export const HOME_BALANCE = {
  amount: 2489.48,
  nextRenewalDate: "2026-03-18T09:00:00.000Z",
};

export const UPCOMING_SUBSCRIPTIONS: UpcomingSubscription[] = [
  {
    id: "spotify",
    icon: icons.spotify,
    name: "Spotify",
    price: 5.99,
    currency: "USD",
    daysLeft: 2,
  },
  {
    id: "notion",
    icon: icons.notion,
    name: "Notion",
    price: 12.0,
    currency: "USD",
    daysLeft: 4,
  },
  {
    id: "figma",
    icon: icons.figma,
    name: "Figma",
    price: 15.0,
    currency: "USD",
    daysLeft: 6,
  },
];

export const SUBSCRIPTION_PACKAGES: SubscriptionPackage[] = [
  {
    id: "spotify",
    icon: icons.spotify,
    name: "Spotify",
    description: "Premium Music Streaming",
    plans: [
      {
        id: "spotify-free",
        name: "Free",
        price: 0,
        currency: "USD",
        features: ["Standard quality", "Ads", "Limited skips"],
      },
      {
        id: "spotify-premium",
        name: "Premium",
        price: 5.99,
        currency: "USD",
        billing: "Monthly",
        features: [
          "High quality audio",
          "No ads",
          "Offline listening",
          "Unlimited skips",
        ],
      },
      {
        id: "spotify-family",
        name: "Family",
        price: 14.99,
        currency: "USD",
        billing: "Monthly",
        features: [
          "Up to 6 accounts",
          "High quality audio",
          "No ads",
          "Family Mix playlist",
        ],
      },
    ],
    color: "#1DB954",
  },
  {
    id: "notion",
    icon: icons.notion,
    name: "Notion",
    description: "All-in-one workspace",
    plans: [
      {
        id: "notion-free",
        name: "Free",
        price: 0,
        currency: "USD",
        features: ["Unlimited blocks", "Basic templates"],
      },
      {
        id: "notion-plus",
        name: "Plus",
        price: 12.0,
        currency: "USD",
        billing: "Monthly",
        features: [
          "30GB file uploads",
          "Priority support",
          "Advanced integrations",
          "Guest invitations",
        ],
      },
      {
        id: "notion-business",
        name: "Business",
        price: 27.0,
        currency: "USD",
        billing: "Monthly",
        features: [
          "1TB file uploads",
          "Advanced security",
          "Advanced API",
          "Admin controls",
        ],
      },
    ],
    color: "#6366F1",
  },
  {
    id: "figma",
    icon: icons.figma,
    name: "Figma",
    description: "Design & Prototyping Platform",
    plans: [
      {
        id: "figma-free",
        name: "Starter",
        price: 0,
        currency: "USD",
        features: ["3 projects", "Unlimited viewers", "Basic features"],
      },
      {
        id: "figma-professional",
        name: "Professional",
        price: 15.0,
        currency: "USD",
        billing: "Monthly",
        features: [
          "Unlimited projects",
          "Unlimited files",
          "Team libraries",
          "Version history",
        ],
      },
      {
        id: "figma-organization",
        name: "Organization",
        price: 45.0,
        currency: "USD",
        billing: "Monthly",
        features: [
          "Workspaces",
          "Advanced permissions",
          "Priority support",
          "SSO",
        ],
      },
    ],
    color: "#0ACE78",
  },
];

export const HOME_SUBSCRIPTIONS: Subscription[] = [
  {
    id: "spotify",
    icon: icons.spotify,
    name: "Spotify",
    plan: "Premium",
    category: "Music",
    paymentMethod: "Visa ending in 8530",
    status: "active",
    startDate: "2025-04-25T10:00:00.000Z",
    price: 5.99,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-04-27T10:00:00.000Z",
    color: "#1DB954",
  },
  {
    id: "notion",
    icon: icons.notion,
    name: "Notion",
    plan: "Plus Plan",
    category: "Productivity",
    paymentMethod: "Mastercard ending in 2408",
    status: "active",
    startDate: "2025-04-25T10:00:00.000Z",
    price: 12.0,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-04-29T10:00:00.000Z",
    color: "#6366F1",
  },
  {
    id: "figma",
    icon: icons.figma,
    name: "Figma",
    plan: "Professional",
    category: "Design",
    paymentMethod: "Amex ending in 1010",
    status: "active",
    startDate: "2025-04-25T10:00:00.000Z",
    price: 15.0,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-05-01T10:00:00.000Z",
    color: "#0ACE78",
  },
  {
    id: "adobe-creative-cloud",
    icon: icons.adobe,
    name: "Adobe Creative Cloud",
    plan: "Teams Plan",
    category: "Design",
    paymentMethod: "Visa ending in 8530",
    status: "active",
    startDate: "2025-03-20T10:00:00.000Z",
    price: 77.49,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-04-27T10:00:00.000Z",
    color: "#f5c542",
  },
  {
    id: "github-pro",
    icon: icons.github,
    name: "GitHub Pro",
    plan: "Developer",
    category: "Developer Tools",
    paymentMethod: "Mastercard ending in 2408",
    status: "active",
    startDate: "2024-11-24T10:00:00.000Z",
    price: 9.99,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-04-29T10:00:00.000Z",
    color: "#e8def8",
  },
  {
    id: "claude-pro",
    icon: icons.claude,
    name: "Claude Pro",
    plan: "Pro Plan",
    category: "AI Tools",
    paymentMethod: "Amex ending in 1010",
    status: "active",
    startDate: "2025-06-27T10:00:00.000Z",
    price: 20.0,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-05-01T10:00:00.000Z",
    color: "#b8d4e3",
  },
  {
    id: "canva-pro",
    icon: icons.canva,
    name: "Canva Pro",
    plan: "Yearly Access",
    category: "Design",
    paymentMethod: "Visa ending in 7784",
    status: "active",
    startDate: "2024-04-02T10:00:00.000Z",
    price: 119.99,
    currency: "USD",
    billing: "Yearly",
    renewalDate: "2026-05-10T10:00:00.000Z",
    color: "#b8e8d0",
  },
];
